### ISSUE TITLE
Assignment 2: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/jeffreypeter#11]
Hi Jeffrey,

Can you send me the Jenkins credentials at ameyaadvankar@gmail.com so that I can check out the jenkins setup.
Also, I didn't find any dockerfile or jenkinsfile in the repository, so how is the build / deployment being done at the moment?

**Comment by jeffreypeter** [comment]
Hi, I have sent you the credentials. Dockerfile method is an alternative method - https://github.com/airavata-courses/jeffreypeter/blob/master/assignment/build/Jenkinsfile.

**Comment by Ameya05** [comment]
Checked out jenkins, build job is setup properly.
