### ISSUE TITLE
Refactor the UI out of the micro-services

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/jeffreypeter#4]
Noticed this while taking a peek at your assignment -

The UI i.e. _index.html_ is within the node.js micro service. 
However, the assignment requires the UI to be separate from the micro-services and the only way the micro-services should be accessed is through an API Server component.

A simple solution to this would be to get the index.html out of the micro-service and create another small independent component API Server to host this index.html file.

**Comment by jeffreypeter** [comment]
Thanks for letting me. I'll add this enhancement.

**Comment by jeffreypeter** [comment]
Completed the enhancement
