### ISSUE TITLE
Virtual env for python

### ISSUE THREAD

**Issue by harsha161992** [airavata-courses/jeffreypeter#5]
Hey,
I have python 3.4(on Windows machine) installed and your steps for installing VM are for Linux. 

I tried the Windows equivalent command by running this - venv\Scripts\activate
And still python --version shows 3.4. 

Can you please check it?

**Comment by jeffreypeter** [comment]
try
py -2 PythonServer.py

or 

> python --version
Python 3.4.2
> set PATH=C:\Python27\;%PATH%
> python --version

**Comment by harsha161992** [comment]
Thanks!

It worked perfectly.
