### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/jeffreypeter#6]
The micro services are well implemented.
The API server or the Gateway component serves its purpose.
Things to be noted:
- Please separate the UI from the Gateway component. As of now the static html and js files are under the same directory as that of the gateway. These should be hosted separately.
- Improve the architecture accordingly

**Comment by marpierc** [comment]
@tilaks26's comment about separating the UI and API server needs to be addressed in your Assignment 2 submission.

**Comment by jeffreypeter** [comment]
sure.

**Comment by jeffreypeter** [comment]
Completed
