### ISSUE TITLE
Which index.html should be run as the UI ?

### ISSUE THREAD

**Issue by nikchett** [airavata-courses/jeffreypeter#8]

**Comment by nikchett** [comment]
Hi ,

Please explain the instruction of using index.html in the same box as gateway.. When i am using that index.html on click of test there is no response.

**Comment by jeffreypeter** [comment]
This index file
https://github.com/airavata-courses/jeffreypeter/blob/master/assignment/index.html
Currently, this index file is hard coded to hit localhost:8000. So it has to run on the same system as gateway.

**Comment by jeffreypeter** [comment]
Currently, the only way to check the output is to check the java docker's console. message is passed from UI > gateway > nodejs > python > java > another Queue
