### ISSUE TITLE
Getting wrong msg while hitting send 

### ISSUE THREAD

**Issue by singhPrasan** [airavata-courses/jeffreypeter#9]
I tried to send a message : "Send Test Message"
When I checked the server console for nodejs, I see a "Hello World" being sent instead of my custom message. Below is the message from server : 
prasan@prasan-Inspiron-3442:~$ sudo docker run --name nodejs -it jeffrav/nodejs

```
Listening at http://localhost:8080
IN::assertExchange
IN::assertQueue
 [*] Waiting for logs. To exit press CTRL+C
Test Send Message:InGateway::InNodejs
IN::test
 [x] Sent 'Hello World!'

```

**Comment by jeffreypeter** [comment]
Its a bug, I'll fix it.

**Comment by jeffreypeter** [comment]
Fixed please retest.
